---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: build
    image: plugins/docker
    settings:
      dry_run: true
      repo: zebardy/openebs-jiva-RW-check
