---
kind: pipeline
type: kubernetes
name: default

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: build
    image: plugins/docker
    settings:
      dry_run: true
      repo: zebardy/openebs-jiva-rw-check
